### ISSUE TITLE
Getting this error at url

### ISSUE THREAD

**Issue by elagrija** [naksyn/Pyramid#13] opened 2024-02-27 07:25 UTC
![MicrosoftTeams-image (2)](https://github.com/naksyn/Pyramid/assets/13571168/c886eab3-877f-40f0-bffd-b3f9a6d527db)

**Comment by elagrija** [comment] 2024-02-27 07:26
Can you help us to solve this

**Comment by naksyn** [comment] 2024-02-27 08:18
The problem is you used 0.0.0.0 as server address. if you're inside a LAN use an address from your private subnet or a public IP otherwise.

**Comment by naksyn** [comment] 2024-02-27 08:20
To clarify, the -server parameter is the IP where the pyramid server is executing and should be reachable from the endpoint where you execute the Pyramid cradle, as I can see from your screenshot, it should be the IP address of your kali machine.

**Comment by elagrija** [comment] 2024-02-27 09:25
thanks for your kind reply. Let me change it as you suggested

**Comment by elagrija** [comment] 2024-02-27 12:10
![embeder](https://github.com/naksyn/Pyramid/assets/13571168/96dd4c28-4eaa-45a3-a19c-eea12f88db0d)  

It is working in pyramid. But not on embeder

**Comment by elagrija** [comment] 2024-02-27 12:11
Kindly look into this.. we are getting socket error

**Comment by elagrija** [comment] 2024-02-27 12:13
![vs code](https://github.com/naksyn/Pyramid/assets/13571168/2a3ab470-bad8-49b0-b7af-2d31eb59e0b0)

**Comment by elagrija** [comment] 2024-02-27 12:14
![dependency files](https://github.com/naksyn/Pyramid/assets/13571168/96384799-f607-4011-8ab0-bbfcfe010f15)

**Comment by elagrija** [comment] 2024-02-27 12:14
Files For your info

**Comment by naksyn** [comment] 2024-02-27 12:40
> ![embeder](https://private-user-images.githubusercontent.com/13571168/308160339-96dd4c28-4eaa-45a3-a19c-eea12f88db0d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzc3NzksIm5iZiI6MTcwOTAzNzQ3OSwicGF0aCI6Ii8xMzU3MTE2OC8zMDgxNjAzMzktOTZkZDRjMjgtNGVhYS00NWEzLWExOWMtZWVhMTJmODhkYjBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyMzc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZWYxYmU1ZmY2OGZlNjQ4Yjc4YTUxYTQ0NzZjYTJmYWJjOTUwNmNhZjI2ZGZhYjg3ZDI0YWZlMzBkYjFlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cSVSHlFEULqMQkcKain1qPx8t3j9usWBVQ3zCQj3q_g)
> 
> It is working in pyramid. But not on embeder

you are getting error on your Pyrami server output. it's not fully readable but looks like you moved the "Delivery_files" folder. you should keep it as it's on the project and put there the files to be loaded with pythonmemorymodule.

**Comment by elagrija** [comment] 2024-02-27 13:16
yes you are right in Pyramid server output ... But no idea  to resolve the execution of embeder.exe ( getting no module named_' socket'). Can you please look into that ? and help us

**Comment by naksyn** [comment] 2024-02-27 14:23
You have to solve like I wrote before. Closing this issue

**Closed by naksyn** 2024-02-27 14:23 UTC
